# Default values for myapp.

# Namespace to deploy into
namespace: default

# Number of replicas
replicaCount: 1

# Container image settings (left empty here—override from CI)
image:
  repository: ""     # e.g. "314525640319.dkr.ecr.il-central-1.amazonaws.com/dor/helm/myapp"
  tag:        ""     # e.g. "12"
  pullPolicy: IfNotPresent
  pullSecrets: []    # e.g. [{ name: "ecr-creds" }]

# The port your container listens on
containerPort: 80

# Resource requests & limits
resources:
  requests:
    cpu:    "100m"
    memory: "128Mi"
  limits:
    cpu:    "200m"
    memory: "256Mi"

# Readiness probe settings
readiness:
  path: "/"
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3

# Liveness probe settings
liveness:
  path: "/"
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 3

# Optional DB secret (leave blank for now)
secret:
  name: ""            # leave empty if not using a Secret
  usernameKey: ""     # e.g. "username" inside that Secret
  passwordKey: ""     # e.g. "password" inside that Secret

# PVC to back /usr/share/nginx/html (leave empty to use emptyDir)
pvcName: ""

# If pvcName is empty, chart will create an emptyDir instead of a PVC.
# If you do want Helm to create a PVC for you, set a storage size & accessModes:
storage:
  size: "1Gi"
  accessModes:
    - ReadWriteOnce

